### ISSUE TITLE
Do entries get persisted to disk?

### ISSUE THREAD

**Issue by chrisguida** [algolia/sup3rS3cretMes5age#41]
Hi, I set supersecretmessage up in production mode, and it appears that secrets input into the app disappear if the docker container is restarted. Is there a simple way to get the data to persist?

Thanks,

--Chris

**Comment by eranchetz** [comment]
Currently sup3rS3cretMes5age does not support persistence (as secrets have short TTL) 

However since the secrets are saved in Vault it has support for storage backends (for example [Filesystem](https://www.vaultproject.io/docs/configuration/storage/filesystem)) 

if create a docker mount and add the following environment variable to the docker-compose.yaml file 
```
'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/vault/file"}}}'
```
the data should persist to disk. 

I am also assuming other [vault storage backends](https://www.vaultproject.io/docs/configuration/storage) can be used to accomplish this

however even though Vault's data is encrypted at rest, you should still take appropriate measures to secure access to the filesystem.

**Comment by chrisguida** [comment]
Excellent, thanks for the reply, I'll try it out
